### ISSUE TITLE
TypeError: main() got an unexpected keyword argument 'single' -bash: syntax error near unexpected token

### ISSUE THREAD

**Issue by dipenpatel235** [axiros/py_gridfs_fuse#1]
[root@dAAA py_gridfs_fuse]# gridfs_fuse --mongodb-uri="mongodb://127.0.0.1:27017" --database="gridfs_fuse" --mount-point="/opt/data_mongo/"
Traceback (most recent call last):
  File "/usr/bin/gridfs_fuse", line 9, in <module>
    load_entry_point('gridfs-fuse==0.1.1', 'console_scripts', 'gridfs_fuse')()
  File "build/bdist.linux-x86_64/egg/gridfs_fuse/main.py", line 68, in main
  File "build/bdist.linux-x86_64/egg/gridfs_fuse/main.py", line 45, in run_fuse_mount
  File "src/fuse_api.pxi", line 273, in llfuse.main (src/llfuse.c:35175)
TypeError: main() got an unexpected keyword argument 'single'
[root@dAAA py_gridfs_fuse]# TypeError: main() got an unexpected keyword argument 'single'
-bash: syntax error near unexpected token `('

**Comment by stephan-hof** [comment]
What version of llfuse are you using ?

**Comment by dipenpatel235** [comment]
llfuse 1.1.1

**Comment by stephan-hof** [comment]
I see llfuse got some development.
When I develop this tool I used llfuse=0.40 => I tested it with that particular version.

I never tested it with newer versions like llfuse=1.1.1.

**Comment by dipenpatel235** [comment]
ok...so which exact version can i used ?
llfuse-0.40 ?

**Comment by stephan-hof** [comment]
Yes 0.40, as I said this is the version I tested/running the code with.
